spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/springbootdemo
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=toilamotnguoivocungdeptraitaigioiconguoiyeuvocungxinhdepnetnathuymuyhieuchuyendangyeudethuonghocgioituyetvoitoimuoonyeucoaymaimaivasecuoicoayvelamvocuatoi

# Google OAuth2 configuration
spring.security.oauth2.client.registration.google.client-id=590209543661-nrt2482a7bl071q8up4ocmdt4urn9ie7.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub